# Generated by Django 5.0.4 on 2024-05-06 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='time_zone',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='country',
            new_name='nit',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='postal_code',
            new_name='phone',
        ),
    ]
