# Generated by Django 5.0.4 on 2024-05-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_rename_time_zone_company_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Branch Name')),
                ('address', models.TextField(verbose_name='Branch Address')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('updated_by', models.CharField(max_length=100, verbose_name='Updated By')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('created_by', models.CharField(max_length=100, verbose_name='Created By')),
                ('email_enabled', models.BooleanField(default=False, verbose_name='Email Notifications Enabled')),
            ],
        ),
    ]
