# Generated by Django 5.0.4 on 2024-05-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_servicearea_branch_agent_count_branch_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='service_areas',
        ),
        migrations.AddField(
            model_name='branch',
            name='service_areas',
            field=models.ManyToManyField(to='company.servicearea', verbose_name='Service Areas'),
        ),
    ]
