# Generated by Django 5.0.4 on 2024-05-12 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_branch_service_areas_branch_service_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='service_areas',
        ),
        migrations.AddField(
            model_name='servicearea',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='company.branch', verbose_name='Branch'),
            preserve_default=False,
        ),
    ]
