# Generated by Django 5.0.4 on 2024-05-13 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_branch_service_areas_servicearea_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Module Name')),
                ('description', models.TextField(verbose_name='Module Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Status')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='company.branch')),
            ],
        ),
    ]
