# Generated by Django 5.0.4 on 2024-05-13 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='config_type',
            field=models.IntegerField(choices=[(1, 'Sin datos del usuario'), (2, 'Con datos del usuario')], default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FieldConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Número'), ('email', 'Email'), ('phone', 'Teléfono'), ('date', 'Fecha'), ('radio', 'Selección Única'), ('dropdown', 'Desplegable'), ('multiselect', 'Selección Múltiple')], max_length=50)),
                ('field_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('placeholder', models.CharField(blank=True, max_length=100)),
                ('required', models.BooleanField(default=False)),
                ('extra_options', models.JSONField(blank=True, null=True)),
                ('service_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='company.servicearea')),
            ],
        ),
    ]
